import Head from 'next/head'
import { Typography, useTheme } from '@mui/material'

export default function Home() {
  const theme = useTheme()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant='h1'>Helloworld</Typography>
    </>
  )
}
